#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlugwiseImporter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class PlugwiseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAppliance(Appliance instance);
    partial void UpdateAppliance(Appliance instance);
    partial void DeleteAppliance(Appliance instance);
    #endregion
		
		public PlugwiseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlugwiseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlugwiseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PlugwiseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Appliance_Log> Appliance_Logs
		{
			get
			{
				return this.GetTable<Appliance_Log>();
			}
		}
		
		public System.Data.Linq.Table<Appliance> Appliances
		{
			get
			{
				return this.GetTable<Appliance>();
			}
		}
		
		public System.Data.Linq.Table<Minute_Log_5> Minute_Log_5s
		{
			get
			{
				return this.GetTable<Minute_Log_5>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Appliance_Log
	{
		
		private System.DateTime _LogDate;
		
		private int _ApplianceID;
		
		private double _Usage_peak;
		
		private double _Usage_offpeak;
		
		public Appliance_Log()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDate")]
		public System.DateTime LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this._LogDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplianceID")]
		public int ApplianceID
		{
			get
			{
				return this._ApplianceID;
			}
			set
			{
				if ((this._ApplianceID != value))
				{
					this._ApplianceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_peak")]
		public double Usage_peak
		{
			get
			{
				return this._Usage_peak;
			}
			set
			{
				if ((this._Usage_peak != value))
				{
					this._Usage_peak = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_offpeak")]
		public double Usage_offpeak
		{
			get
			{
				return this._Usage_offpeak;
			}
			set
			{
				if ((this._Usage_offpeak != value))
				{
					this._Usage_offpeak = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Appliance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Type;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Appliance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Minute_Log_5
	{
		
		private int _ApplianceID;
		
		private System.DateTime _LogDate;
		
		private System.DateTime _ChangedDate;
		
		private System.Nullable<double> _Usage_00;
		
		private System.Nullable<double> _Usage_05;
		
		private System.Nullable<double> _Usage_10;
		
		private System.Nullable<double> _Usage_15;
		
		private System.Nullable<double> _Usage_20;
		
		private System.Nullable<double> _Usage_25;
		
		private System.Nullable<double> _Usage_30;
		
		private System.Nullable<double> _Usage_35;
		
		private System.Nullable<double> _Usage_40;
		
		private System.Nullable<double> _Usage_45;
		
		private System.Nullable<double> _Usage_50;
		
		private System.Nullable<double> _Usage_55;
		
		public Minute_Log_5()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplianceID")]
		public int ApplianceID
		{
			get
			{
				return this._ApplianceID;
			}
			set
			{
				if ((this._ApplianceID != value))
				{
					this._ApplianceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDate")]
		public System.DateTime LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this._LogDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangedDate")]
		public System.DateTime ChangedDate
		{
			get
			{
				return this._ChangedDate;
			}
			set
			{
				if ((this._ChangedDate != value))
				{
					this._ChangedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_00")]
		public System.Nullable<double> Usage_00
		{
			get
			{
				return this._Usage_00;
			}
			set
			{
				if ((this._Usage_00 != value))
				{
					this._Usage_00 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_05")]
		public System.Nullable<double> Usage_05
		{
			get
			{
				return this._Usage_05;
			}
			set
			{
				if ((this._Usage_05 != value))
				{
					this._Usage_05 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_10")]
		public System.Nullable<double> Usage_10
		{
			get
			{
				return this._Usage_10;
			}
			set
			{
				if ((this._Usage_10 != value))
				{
					this._Usage_10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_15")]
		public System.Nullable<double> Usage_15
		{
			get
			{
				return this._Usage_15;
			}
			set
			{
				if ((this._Usage_15 != value))
				{
					this._Usage_15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_20")]
		public System.Nullable<double> Usage_20
		{
			get
			{
				return this._Usage_20;
			}
			set
			{
				if ((this._Usage_20 != value))
				{
					this._Usage_20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_25")]
		public System.Nullable<double> Usage_25
		{
			get
			{
				return this._Usage_25;
			}
			set
			{
				if ((this._Usage_25 != value))
				{
					this._Usage_25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_30")]
		public System.Nullable<double> Usage_30
		{
			get
			{
				return this._Usage_30;
			}
			set
			{
				if ((this._Usage_30 != value))
				{
					this._Usage_30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_35")]
		public System.Nullable<double> Usage_35
		{
			get
			{
				return this._Usage_35;
			}
			set
			{
				if ((this._Usage_35 != value))
				{
					this._Usage_35 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_40")]
		public System.Nullable<double> Usage_40
		{
			get
			{
				return this._Usage_40;
			}
			set
			{
				if ((this._Usage_40 != value))
				{
					this._Usage_40 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_45")]
		public System.Nullable<double> Usage_45
		{
			get
			{
				return this._Usage_45;
			}
			set
			{
				if ((this._Usage_45 != value))
				{
					this._Usage_45 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_50")]
		public System.Nullable<double> Usage_50
		{
			get
			{
				return this._Usage_50;
			}
			set
			{
				if ((this._Usage_50 != value))
				{
					this._Usage_50 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage_55")]
		public System.Nullable<double> Usage_55
		{
			get
			{
				return this._Usage_55;
			}
			set
			{
				if ((this._Usage_55 != value))
				{
					this._Usage_55 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
